const mobileViewSwitcher = document.getElementById('mobileViewSwitcher');

export const dom = {
  editor: document.getElementById('editor'),
  preview: document.getElementById('preview'),
  themeToggle: document.getElementById('themeToggle'),
  editorPane: document.getElementById('editorPane'),
  previewPane: document.getElementById('previewPane'),
  collapseBtn: document.getElementById('collapseEditor'),
  resizeHandle: document.getElementById('resizeHandle'),
  mobileViewSwitcher,
  viewTabs: mobileViewSwitcher ? mobileViewSwitcher.querySelectorAll('.view-tab') : [],
  scrollSyncToggle: document.getElementById('scrollSyncToggle'),
  lintToggle: document.getElementById('lintToggle'),
  lintCount: document.getElementById('lintCount'),
  lintPanel: document.getElementById('lintPanel'),
  lintList: document.getElementById('lintList'),
  lineGutter: document.getElementById('lineGutter'),
  exportMenu: document.getElementById('exportMenu'),
  exportMenuBtn: document.getElementById('exportMenuBtn'),
  exportMenuPopover: document.getElementById('exportMenuPopover'),
  exportMdBtn: document.getElementById('exportMdBtn'),
  exportHtmlBtn: document.getElementById('exportHtmlBtn'),
  exportPdfBtn: document.getElementById('exportPdfBtn'),
  exportDialog: document.getElementById('exportDialog'),
  exportDialogTitle: document.getElementById('exportDialogTitle'),
  exportDialogDesc: document.getElementById('exportDialogDesc'),
  exportEmbedImagesField: document.getElementById('exportEmbedImagesField'),
  exportFilenameInput: document.getElementById('exportFilename'),
  exportThemeSelect: document.getElementById('exportTheme'),
  exportEmbedImages: document.getElementById('exportEmbedImages'),
  exportCancelBtn: document.getElementById('exportCancelBtn'),
  exportDownloadBtn: document.getElementById('exportDownloadBtn'),
  importBtn: document.getElementById('importBtn'),
  importFileInput: document.getElementById('importFileInput'),
  importConfirmDialog: document.getElementById('importConfirmDialog'),
  importConfirmDesc: document.getElementById('importConfirmDesc'),
  importConfirmCancelBtn: document.getElementById('importConfirmCancelBtn'),
  importConfirmReplaceBtn: document.getElementById('importConfirmReplaceBtn'),
  mediaViewerDialog: document.getElementById('mediaViewerDialog'),
  mediaViewerStage: document.getElementById('mediaViewerStage'),
  mediaViewerClose: document.getElementById('mediaViewerClose'),
  html: document.documentElement,
};
